# Generated by Django 5.2.1 on 2026-02-08 01:00

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True)),
                ('clasificacion', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para inhabilitar esta entrada del diccionario', verbose_name='activo')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, verbose_name='segundo nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, verbose_name='segundo apellido')),
                ('cedula', models.BigIntegerField(null=True, unique=True, verbose_name='cedula')),
                ('telefono', models.BigIntegerField(verbose_name='telefono')),
                ('security_question', models.CharField(max_length=255, verbose_name='pregunta de seguridad')),
                ('security_answer', models.CharField(max_length=255, verbose_name='respuesta de seguridad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', tasks.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cota', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(max_length=100)),
                ('co_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.IntegerField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('edicion', models.PositiveSmallIntegerField(choices=[(1, '1ª ed.'), (2, '2ª ed.'), (3, '3ª ed.'), (4, '4ª ed.'), (5, '5ª ed.'), (6, '6ª ed.'), (7, '7ª ed.'), (8, '8ª ed.'), (9, '9ª ed.'), (10, '10ª ed.'), (11, '11ª ed.'), (12, '12ª ed.'), (13, '13ª ed.'), (14, '14ª ed.'), (15, '15ª ed.'), (16, '16ª ed.'), (17, '17ª ed.'), (18, '18ª ed.'), (19, '19ª ed.'), (20, '20ª ed.'), (21, '21ª ed.'), (22, '22ª ed.'), (23, '23ª ed.'), (24, '24ª ed.'), (25, '25ª ed.'), (26, '26ª ed.'), (27, '27ª ed.'), (28, '28ª ed.'), (29, '29ª ed.'), (30, '30ª ed.'), (31, '31ª ed.'), (32, '32ª ed.'), (33, '33ª ed.'), (34, '34ª ed.'), (35, '35ª ed.'), (36, '36ª ed.'), (37, '37ª ed.'), (38, '38ª ed.'), (39, '39ª ed.'), (40, '40ª ed.'), (41, '41ª ed.'), (42, '42ª ed.'), (43, '43ª ed.'), (44, '44ª ed.'), (45, '45ª ed.'), (46, '46ª ed.'), (47, '47ª ed.'), (48, '48ª ed.'), (49, '49ª ed.')], default=1, verbose_name='edición')),
                ('ubicacion_publicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('volumen', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 v.'), (2, '2 v.'), (3, '3 v.'), (4, '4 v.'), (5, '5 v.'), (6, '6 v.'), (7, '7 v.'), (8, '8 v.'), (9, '9 v.'), (10, '10 v.'), (11, '11 v.'), (12, '12 v.'), (13, '13 v.'), (14, '14 v.'), (15, '15 v.'), (16, '16 v.'), (17, '17 v.'), (18, '18 v.'), (19, '19 v.'), (20, '20 v.'), (21, '21 v.'), (22, '22 v.'), (23, '23 v.'), (24, '24 v.'), (25, '25 v.'), (26, '26 v.'), (27, '27 v.'), (28, '28 v.'), (29, '29 v.'), (30, '30 v.'), (31, '31 v.'), (32, '32 v.'), (33, '33 v.'), (34, '34 v.'), (35, '35 v.'), (36, '36 v.'), (37, '37 v.'), (38, '38 v.'), (39, '39 v.'), (40, '40 v.'), (41, '41 v.'), (42, '42 v.'), (43, '43 v.'), (44, '44 v.'), (45, '45 v.'), (46, '46 v.'), (47, '47 v.'), (48, '48 v.'), (49, '49 v.'), (50, '50 v.'), (51, '51 v.'), (52, '52 v.'), (53, '53 v.'), (54, '54 v.'), (55, '55 v.'), (56, '56 v.'), (57, '57 v.'), (58, '58 v.'), (59, '59 v.'), (60, '60 v.'), (61, '61 v.'), (62, '62 v.'), (63, '63 v.'), (64, '64 v.'), (65, '65 v.'), (66, '66 v.'), (67, '67 v.'), (68, '68 v.'), (69, '69 v.'), (70, '70 v.'), (71, '71 v.'), (72, '72 v.'), (73, '73 v.'), (74, '74 v.'), (75, '75 v.'), (76, '76 v.'), (77, '77 v.'), (78, '78 v.'), (79, '79 v.'), (80, '80 v.'), (81, '81 v.'), (82, '82 v.'), (83, '83 v.'), (84, '84 v.'), (85, '85 v.'), (86, '86 v.'), (87, '87 v.'), (88, '88 v.'), (89, '89 v.'), (90, '90 v.'), (91, '91 v.'), (92, '92 v.'), (93, '93 v.'), (94, '94 v.'), (95, '95 v.'), (96, '96 v.'), (97, '97 v.'), (98, '98 v.'), (99, '99 v.')], null=True, verbose_name='volumen')),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad disponible en el inventario', verbose_name='cantidad')),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.IntegerField(blank=True, null=True)),
                ('numero_registro', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('hora_creacion', models.TimeField(auto_now_add=True, null=True, verbose_name='hora de creación')),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('portada', models.ImageField(blank=True, help_text='Imagen de portada (opcional)', null=True, upload_to='covers/', verbose_name='portada')),
                ('contenido', models.CharField(blank=True, help_text='Seleccione los contenidos (guardado como valores separados por comas)', max_length=200, null=True, verbose_name='contenido del libro')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para inhabilitar este libro sin borrarlo', verbose_name='activo')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='tasks.clasificacion')),
                ('dictionary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='tasks.dictionaryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('pdf', 'PDF Print'), ('login', 'Login')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tasks.libros')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('receiver_cedula', models.CharField(blank=True, max_length=32, null=True, verbose_name='cédula receptor')),
                ('receiver_first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre receptor')),
                ('receiver_last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='apellido receptor')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto')], default='active', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_report', models.TextField(blank=True, null=True, verbose_name='reporte devolución')),
                ('return_book_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntuación libro')),
                ('return_receiver_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntuación receptor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='tasks.libros')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
