# Generated by Django 5.2.1 on 2025-09-13 00:35

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='materia')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tasks.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='libros',
            name='contenido',
            field=models.CharField(blank=True, help_text='Seleccione los contenidos (guardado como valores separados por comas)', max_length=200, null=True, verbose_name='contenido del libro'),
        ),
        migrations.AddField(
            model_name='libros',
            name='datos_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='edicion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1ª ed.'), (2, '2ª ed.'), (3, '3ª ed.'), (4, '4ª ed.'), (5, '5ª ed.'), (6, '6ª ed.'), (7, '7ª ed.'), (8, '8ª ed.'), (9, '9ª ed.'), (10, '10ª ed.'), (11, '11ª ed.'), (12, '12ª ed.'), (13, '13ª ed.'), (14, '14ª ed.'), (15, '15ª ed.'), (16, '16ª ed.'), (17, '17ª ed.'), (18, '18ª ed.'), (19, '19ª ed.'), (20, '20ª ed.'), (21, '21ª ed.'), (22, '22ª ed.'), (23, '23ª ed.'), (24, '24ª ed.'), (25, '25ª ed.'), (26, '26ª ed.'), (27, '27ª ed.'), (28, '28ª ed.'), (29, '29ª ed.'), (30, '30ª ed.'), (31, '31ª ed.'), (32, '32ª ed.'), (33, '33ª ed.'), (34, '34ª ed.'), (35, '35ª ed.'), (36, '36ª ed.'), (37, '37ª ed.'), (38, '38ª ed.'), (39, '39ª ed.'), (40, '40ª ed.'), (41, '41ª ed.'), (42, '42ª ed.'), (43, '43ª ed.'), (44, '44ª ed.'), (45, '45ª ed.'), (46, '46ª ed.'), (47, '47ª ed.'), (48, '48ª ed.'), (49, '49ª ed.')], default=1, verbose_name='edición'),
        ),
        migrations.AddField(
            model_name='libros',
            name='numero_serie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='ubicacion_publicacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='volumen',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 v.'), (2, '2 v.'), (3, '3 v.'), (4, '4 v.'), (5, '5 v.'), (6, '6 v.'), (7, '7 v.'), (8, '8 v.'), (9, '9 v.'), (10, '10 v.'), (11, '11 v.'), (12, '12 v.'), (13, '13 v.'), (14, '14 v.'), (15, '15 v.'), (16, '16 v.'), (17, '17 v.'), (18, '18 v.'), (19, '19 v.'), (20, '20 v.'), (21, '21 v.'), (22, '22 v.'), (23, '23 v.'), (24, '24 v.'), (25, '25 v.'), (26, '26 v.'), (27, '27 v.'), (28, '28 v.'), (29, '29 v.'), (30, '30 v.'), (31, '31 v.'), (32, '32 v.'), (33, '33 v.'), (34, '34 v.'), (35, '35 v.'), (36, '36 v.'), (37, '37 v.'), (38, '38 v.'), (39, '39 v.'), (40, '40 v.'), (41, '41 v.'), (42, '42 v.'), (43, '43 v.'), (44, '44 v.'), (45, '45 v.'), (46, '46 v.'), (47, '47 v.'), (48, '48 v.'), (49, '49 v.'), (50, '50 v.'), (51, '51 v.'), (52, '52 v.'), (53, '53 v.'), (54, '54 v.'), (55, '55 v.'), (56, '56 v.'), (57, '57 v.'), (58, '58 v.'), (59, '59 v.'), (60, '60 v.'), (61, '61 v.'), (62, '62 v.'), (63, '63 v.'), (64, '64 v.'), (65, '65 v.'), (66, '66 v.'), (67, '67 v.'), (68, '68 v.'), (69, '69 v.'), (70, '70 v.'), (71, '71 v.'), (72, '72 v.'), (73, '73 v.'), (74, '74 v.'), (75, '75 v.'), (76, '76 v.'), (77, '77 v.'), (78, '78 v.'), (79, '79 v.'), (80, '80 v.'), (81, '81 v.'), (82, '82 v.'), (83, '83 v.'), (84, '84 v.'), (85, '85 v.'), (86, '86 v.'), (87, '87 v.'), (88, '88 v.'), (89, '89 v.'), (90, '90 v.'), (91, '91 v.'), (92, '92 v.'), (93, '93 v.'), (94, '94 v.'), (95, '95 v.'), (96, '96 v.'), (97, '97 v.'), (98, '98 v.'), (99, '99 v.')], null=True, verbose_name='volumen'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_publicacion',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(null=True, unique=True, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='libros',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='libros', to='tasks.materia'),
        ),
    ]
