# Generated by Django 5.2.1 on 2026-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('trabajador', 'Trabajador'), ('superusuario', 'Superusuario')], default='usuario', max_length=20, verbose_name='rol'),
        ),
    ]
