# Generated by Django 5.2.1 on 2026-02-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
