# Generated by Django 5.2.1 on 2025-09-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_materia_alter_user_managers_libros_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
