# Generated by Django 5.2.1 on 2026-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('pending', 'Pendiente Aprobación'), ('return_pending', 'Pendiente Devolución')], default='active', max_length=20),
        ),
    ]
