# Generated by Django 5.2.1 on 2025-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_libros_dimensiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
