# Generated by Django 5.2.1 on 2025-09-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_libros_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='editorial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
