# Generated by Django 5.2.1 on 2025-09-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_libros_editorial_alter_libros_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='ubicacion_publicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
