# Generated by Django 5.2.1 on 2025-09-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_libros_ubicacion_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, help_text='Imagen de portada (opcional)', null=True, upload_to='covers/', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
