# Generated by Django 5.2.1 on 2025-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad disponible en el inventario', verbose_name='cantidad'),
        ),
    ]
