# Generated by Django 5.2.1 on 2025-09-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
