# Generated by Django 5.2.1 on 2025-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_dictionaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
