# Generated by Django 5.2.1 on 2025-10-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_dictionaryentry_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='dictionary_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='tasks.dictionaryentry'),
        ),
    ]
