# Generated by Django 5.2.1 on 2025-10-01 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_libros_dictionary_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='libros',
            name='materias',
        ),
        migrations.AddField(
            model_name='libros',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='tasks.clasificacion'),
        ),
    ]
