"""
Migration to remove the obsolete Materia model (the model class was deleted from models.py).
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_clasificacion_remove_libros_materias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
# Generated by Django 5.2.1 on 2025-10-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_clasificacion_remove_libros_materias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
