# Generated by Django 5.2.1 on 2025-10-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_add_prestamo_receiver_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='receiver_cedula',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='cédula receptor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre receptor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='apellido receptor'),
        ),
    ]
