# Generated by Django 5.2.1 on 2025-10-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_prestamo_receiver_cedula_and_more'),
        ('tasks', '0022_add_libros_creation_fields'),
    ]

    operations = [
    ]
