# Generated by Django 5.2.1 on 2025-10-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_add_libros_creation_fields'),
        ('tasks', '0023_merge_20251007_1312'),
    ]

    operations = [
    ]
