# Generated by Django 5.2.1 on 2025-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_20251007_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para inhabilitar esta entrada del diccionario', verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='libros',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para inhabilitar este libro sin borrarlo', verbose_name='activo'),
        ),
    ]
