# Generated by Django 5.2.1 on 2025-10-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_dictionaryentry_is_active_libros_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
