# Generated by Django 5.2.1 on 2025-10-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_prestamo_approved_at_prestamo_returned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='created_at',
        ),
    ]
