# Generated by Django 5.2.1 on 2025-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_prestamo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='return_book_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntuación libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='return_receiver_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puntuación receptor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='return_report',
            field=models.TextField(blank=True, null=True, verbose_name='reporte devolución'),
        ),
    ]
