# Generated by Django 5.2.1 on 2026-02-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_prestamo_return_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(verbose_name='telefono'),
        ),
    ]
